<div style="display: flex; align-items: center; justify-content: center; flex-wrap: wrap;">
    <div style="flex: 1; max-width: 400px; display: flex; justify-content: center;">
        <img src="https://magic.novaims.unl.pt/media/1tdf2arr/ims25_horizontal__positivo_rgb.svg" style="max-width: 50%; height: auto; margin-top: 50px; margin-bottom: 50px;margin-left: 6rem;">
    </div>
    <div style="flex: 2; text-align: center; margin-top: 20px;margin-left: 6rem;">
        <div style="font-size: 28px; font-weight: bold; line-height: 1.2;">
            <span style="color: #FFCD41;">Thesis Project |</span> <span style="color: #F58228;">LLM-Powered Urban Exploration: A Framework for Adaptive Tourist and Mobility Route Planning</span>
        </div>
        <div style="font-size: 17px; font-weight: bold; margin-top: 10px;">
            2025 - 2026
        </div>
        <div style="font-size: 17px; font-weight: bold;">
            Master in Data Science and Advanced Analytics
        </div>
        <div style="margin-top: 20px;">
            <div>André Filipe Gomes Silvestre, 20240502</div>
        </div>
    </div>
</div>

<style>
@import url('https://fonts.cdnfonts.com/css/avenir-next-lt-pro?styles=29974');
</style>

<div style="background: linear-gradient(to right, #F58228, #FFCD41);
            padding: 15px; color: white; border-radius: 300px; text-align: center;">
    <center><h1 style="margin-left: 100px;margin-top: 10px; margin-bottom: 4px; color: white;
                       font-size: 32px; font-family: 'Avenir Next LT Pro', sans-serif;"><b>1 & 2 | Business & Data Understanding</b></h1></center>
</div>

<br><br>


## **📝 Project Overview**

AAAAAAAAAAA

### **🔎 Dataset Attributes**

<center><b>Table 1 | </b> Dataset Attributes with Descriptions. <br>

<br>

|       | **Field**                          | **Description**                                                                 | **Type**     |
|-------|------------------------------------|---------------------------------------------------------------------------------|--------------|
| **1** | `url`                              | URL of the event or place                                                        | Text         |
| **2** | `category`                         | Category classification of the event or place                                   | Categorical  |
| **3** | `image_urls`                       | List of image URLs associated with the event or place                           | List         |
| **4** | `video_urls`                       | List of video URLs associated with the event or place                           | List         |
| **5** | `full_description`                 | Detailed description of the event or place                                      | Text         |
| **6** | `dates`                            | Dates related to the event (only in `events.json`)                              | List         |
| **7** | `information_links`                | Additional information links for the event                                      | Object       |
| **8** | `title`                            | Title of the place (only in places.json)                                        | Text         |
| **9** | `short_description`                | Short description of the place (only in places.json)                            | Text         |
| **10**| `features`                         | List of features of the place (only in places.json)                             | List         |
| **11**| `contact_info`                     | Contact information for the place (only in places.json)                         | Object       |
| **12**| `social_media`                     | Social media links for the place (only in places.json)                          | Object       |
| **13**| `schedule`                         | Operating schedule for the place (only in places.json)                          | Object       |
| **14**| `location`                         | Location details of the place (only in places.json)                             | Text         |
| **15**| `tripadvisor`                      | TripAdvisor information for the place (only in places.json)                     | Object       |

</center>

<br><br>

## <span style="color: #ffffff;">Title</span>
<style>
@import url('https://fonts.cdnfonts.com/css/avenir-next-lt-pro?styles=29974');
</style>

<div style="background: transparent;
            padding: 10px; color: white; border-radius: 300px; text-align: center;
            border: 2px solid #F58228;">
    <center><h2 style="margin-left: 120px;margin-top: 10px; margin-bottom: 4px; color: #F58228;
                       font-size: 24px; font-family: 'Avenir Next LT Pro', sans-serif;"><b> Title</b></h2></center>
</div>

<br><br>

In [ ]:
# Install the required packages
# !pip install json pandas plotly

In [ ]:
# Import necessary libraries
import json
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
# Load the JSON files
with open('events.json', 'r', encoding='utf-8') as f:
    events_data = json.load(f)

with open('places.json', 'r', encoding='utf-8') as f:
    places_data = json.load(f)

# Convert to DataFrames
events_df = pd.DataFrame(events_data)
places_df = pd.DataFrame(places_data)

In [8]:
# Count the number of observations in each file
num_events = len(events_df)
num_places = len(places_df)

print(f"Number of observations in events.json: {num_events}")
print(f"Number of observations in places.json: {num_places}")

Number of observations in events.json: 160
Number of observations in places.json: 1170

In [16]:
# Frequency table for events.json categories
events_freq = events_df['category'].value_counts().reset_index()
events_freq.columns = ['Category', 'n']
events_freq['%'] = (events_freq['n'] / events_freq['n'].sum() * 100).round(2)

print("Frequency table for events.json:")
events_freq

Frequency table for events.json:

                Category   n      %
0            Exhibitions  40  25.32
1                  Music  38  24.05
2            Main Events  34  21.52
3                  Fairs  14   8.86
4              Festivals  11   6.96
5  Theater Opera & Dance  10   6.33
6                 Sports   4   2.53
7                 Others   4   2.53
8                 Cinema   3   1.90

In [15]:
# Frequency table for places.json categories
places_freq = places_df['category'].value_counts().reset_index()
places_freq.columns = ['Category', 'n']
places_freq['%'] = (places_freq['n'] / places_freq['n'].sum() * 100).round(2)

print("Frequency table for places.json:")
places_freq

Frequency table for places.json:

                         Category    n      %
0                           Hotel  224  22.65
1                      Restaurant  114  11.53
2                           Tours  113  11.43
3                         Museums   68   6.88
4                       Monuments   61   6.17
5             Museums & Monuments   43   4.35
6   Apartments & Hotel Apartments   34   3.44
7                     DMCS & PCOS   31   3.13
8                        Shopping   30   3.03
9                 Tourist Offices   27   2.73
10                         Nature   23   2.33
11                    View Points   20   2.02
12    Local & Rural Accommodation   16   1.62
13                   Tejo Cruises   16   1.62
14       Cultural centres & trips   13   1.31
15                    Attractions   13   1.31
16                   Guest Houses   12   1.21
17                       18 Holes   12   1.21
18                 Only in Lisbon   11   1.11
19               Cultural Centres   10   1.01
20                        Hostels    7   0.71
21                           Fado    7   0.71
22                         Venues    7   0.71
23                   Other Sports    6   0.61
24             Meeting Facilities    6   0.61
25                    Coffee shop    6   0.61
26         Golfs Links & Sea View    6   0.61
27                  Family & Kids    5   0.51
28                     Enoturismo    4   0.40
29                        Running    4   0.40
30                       Pousadas    4   0.40
31                   Water Sports    3   0.30
32       Nature & Adventure Tours    3   0.30
33              Sightseeing Tours    3   0.30
34                        Camping    3   0.30
35                     Surf Spots    3   0.30
36            Restaurants & Cafes    3   0.30
37               Bars & Nightlife    2   0.20
38              Traditional Boats    2   0.20
39                           Golf    2   0.20
40        Nautical Tours & Others    2   0.20
41               Natural Reserves    2   0.20
42                        9 Holes    2   0.20
43                Marinas & Ports    2   0.20
44          National Surf Reserve    1   0.10
45                        Beaches    1   0.10
46    Culture, Art & Architecture    1   0.10
47                  Private Tours    1   0.10

In [14]:
# Combined frequency table
events_freq['Source'] = 'Events'
places_freq['Source'] = 'Places'
combined_freq = pd.concat([events_freq, places_freq])
combined_freq = combined_freq.groupby('Category')['n'].sum().reset_index()
combined_freq['%'] = (combined_freq['n'] / combined_freq['n'].sum() * 100).round(2)
combined_freq = combined_freq.sort_values('n', ascending=False)

print("Combined frequency table:")
combined_freq

Combined frequency table:

                         Category    n      %
23                          Hotel  224  19.53
42                     Restaurant  114   9.94
52                          Tours  113   9.85
29                        Museums   68   5.93
28                      Monuments   61   5.32
30            Museums & Monuments   43   3.75
14                    Exhibitions   40   3.49
31                          Music   38   3.31
2   Apartments & Hotel Apartments   34   2.96
25                    Main Events   34   2.96
12                    DMCS & PCOS   31   2.70
45                       Shopping   30   2.62
51                Tourist Offices   27   2.35
34                         Nature   23   2.01
55                    View Points   20   1.74
49                   Tejo Cruises   16   1.39
24    Local & Rural Accommodation   16   1.39
16                          Fairs   14   1.22
3                     Attractions   13   1.13
10       Cultural centres & trips   13   1.13
0                        18 Holes   12   1.05
21                   Guest Houses   12   1.05
18                      Festivals   11   0.96
37                 Only in Lisbon   11   0.96
9                Cultural Centres   10   0.87
50          Theater Opera & Dance   10   0.87
22                        Hostels    7   0.61
54                         Venues    7   0.61
15                           Fado    7   0.61
38                   Other Sports    6   0.52
20         Golfs Links & Sea View    6   0.52
8                     Coffee shop    6   0.52
27             Meeting Facilities    6   0.52
17                  Family & Kids    5   0.44
44                        Running    4   0.35
39                         Others    4   0.35
47                         Sports    4   0.35
40                       Pousadas    4   0.35
13                     Enoturismo    4   0.35
6                         Camping    3   0.26
7                          Cinema    3   0.26
56                   Water Sports    3   0.26
48                     Surf Spots    3   0.26
43            Restaurants & Cafes    3   0.26
46              Sightseeing Tours    3   0.26
35       Nature & Adventure Tours    3   0.26
1                         9 Holes    2   0.17
4                Bars & Nightlife    2   0.17
19                           Golf    2   0.17
53              Traditional Boats    2   0.17
33               Natural Reserves    2   0.17
26                Marinas & Ports    2   0.17
36        Nautical Tours & Others    2   0.17
11    Culture, Art & Architecture    1   0.09
5                         Beaches    1   0.09
32          National Surf Reserve    1   0.09
41                  Private Tours    1   0.09

In [12]:
# Create a bar chart in yellow tones for Lisbon categories
fig = px.bar(combined_freq, x='Category', y='n', 
             title='Frequency of Categories in Lisbon Events and Places Data',
             labels={'n': 'Count', 'Category': 'Category'},
             color_discrete_sequence=['#FFD700', '#FFA500', '#FFFF00', '#F0E68C', '#DAA520'])  # Yellow tones

# Update layout for better appearance
fig.update_layout(
    xaxis_tickangle=-45,
    font=dict(size=12),
    title_font_size=16
)

fig.show()